// ============================================================
//  NINH BÌNH AI — Ăn vặt
//  File: anvat.js
// ============================================================

const SNACKS = [
  {
    name: 'Kem Xôi Thanh Hằng',
    nameEn: 'Thanh Hang Sticky Rice Ice Cream',
    lat: 20.2572, lng: 105.9705,
    color: '#ec4899', type: 'snack', priority: true,
    location: '36 Cù Chính Lan (Phố 8), Tân Thành, Ninh Bình',
    locationEn: '36 Cu Chinh Lan (Pho 8), Tan Thanh, Ninh Binh',
    price: '15.000 – 40.000đ/cốc', priceEn: '15,000 – 40,000 VND/cup',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn vặt kinh điển và nổi tiếng nhất Ninh Bình. Kem xôi dẻo thơm, kem béo ngậy, thường ăn kèm bánh đa giòn. Luôn đông khách từ sáng đến tối muộn.',
    noteEn: 'The most legendary sticky rice ice cream in Ninh Binh. Creamy, fragrant and addictive. Often paired with crispy rice crackers.',
  },
  {
    name: 'Thịt Xiên Nướng Đức Trọc',
    nameEn: 'Duc Troc Grilled Skewers',
    lat: 20.2605, lng: 105.9750,
    color: '#ec4899', type: 'snack', priority: true,
    location: '52 Hoàng Hoa Thám, Vân Giang, TP. Ninh Bình',
    locationEn: '52 Hoang Hoa Tham Street, Van Giang, Ninh Binh City',
    price: '5.000 – 20.000đ/xiên', priceEn: '5,000 – 20,000 VND/skewer',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thịt xiên nướng nổi tiếng giới trẻ Ninh Bình. Thịt ướp đậm đà, nướng thơm lừng. Giá rẻ, ăn vặt rất hợp.',
    noteEn: 'Popular grilled skewers loved by local youth. Well-marinated meat, fragrant and affordable.',
  },
  {
    name: 'Chè Bưởi An Giang',
    nameEn: 'An Giang Grapefruit Sweet Soup',
    lat: 20.2560, lng: 105.9720,
    color: '#ec4899', type: 'snack', priority: true,
    location: '14 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: '14 Luong Van Tuy Street, Tan Thanh, Ninh Binh',
    price: '15.000 – 25.000đ', priceEn: '15,000 – 25,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Chè bưởi chuẩn vị, cùi bưởi giòn, đậu xanh mềm, nước cốt dừa béo ngậy. Món ăn vặt mát lạnh được khen ngon nhất Ninh Bình.',
    noteEn: 'Grapefruit sweet soup with crunchy pomelo, soft mung beans and rich coconut milk. Highly recommended.',
  },
  {
    name: 'Bánh Mì Cố Đô',
    nameEn: 'Co Do Banh Mi',
    lat: 20.2555, lng: 105.9725,
    color: '#ec4899', type: 'snack', priority: true,
    location: '117 Lương Văn Tụy, Hoa Lư, Ninh Bình',
    locationEn: '117 Luong Van Tuy Street, Hoa Lu, Ninh Binh',
    price: '20.000 – 35.000đ/ổ', priceEn: '20,000 – 35,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Bánh mì nóng giòn, nhân đầy ú ụ. Có chương trình tặng nước đậu miễn phí. Được giới trẻ và du khách yêu thích.',
    noteEn: 'Crispy hot baguette with generous fillings. Often offers free soy milk. Popular among locals and tourists.',
  },
  {
    name: 'Bánh Mì Chảo Bánh Mì Giòn',
    nameEn: 'Banh Mi Chao - Banh Mi Gion',
    lat: 20.2568, lng: 105.9728,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 7, Ngõ 43 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 7, Alley 43 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '15.000 – 45.000đ', priceEn: '15,000 – 45,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh mì chảo nóng giòn nổi tiếng đường Lương Văn Tụy. Ăn kèm pate, trứng, xúc xích, chả... rất hợp ăn sáng hoặc ăn vặt muộn.',
    noteEn: 'Famous hot crispy pan-fried banh mi. Served with pate, egg, sausage, etc. Great for breakfast or late-night snack.',
  },
  {
    name: 'Nem Nướng Nha Trang',
    nameEn: 'Nha Trang Grilled Spring Rolls',
    lat: 20.2630, lng: 105.9685,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Công viên Thúy Sơn, đường Lê Đại Hành, TP. Ninh Bình',
    locationEn: 'Thuy Son Park, Le Dai Hanh Street, Ninh Binh City',
    price: '40.000 – 80.000đ/phần', priceEn: '40,000 – 80,000 VND/serving',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Nem nướng kiểu Nha Trang, ăn kèm rau sống, bánh tráng, nước chấm đặc trưng. Không gian công viên thoáng mát.',
    noteEn: 'Nha Trang-style grilled spring rolls with fresh herbs, rice paper and signature dipping sauce. Nice park atmosphere.',
  },
  {
    name: 'Bánh Rán Phố Cổ',
    nameEn: 'Old Quarter Fried Pancakes',
    lat: 20.2492, lng: 105.9772,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Khu ẩm thực đường phố Phố cổ Hoa Lư',
    locationEn: 'Street Food Area, Hoa Lu Old Quarter',
    price: '5.000 – 15.000đ/chiếc', priceEn: '5,000 – 15,000 VND/piece',
    bestTime: 'Buổi tối', bestTimeEn: 'Evening',
    note: 'Bánh rán nóng giòn tan, ăn kèm nước mắm chua ngọt. Món ăn vặt không thể bỏ qua khi dạo Phố cổ về đêm.',
    noteEn: 'Crispy hot fried pancakes with sweet and sour dipping sauce. Must-try street snack in the Old Quarter at night.',
  },
  {
    name: 'Bún Canh Cu Tý',
    nameEn: 'Bun Canh Cu Ty',
    lat: 20.2565, lng: 105.9722,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 8, Ngõ 75 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 8, Alley 75 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '20.000 – 40.000đ/bát', priceEn: '20,000 – 40,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Bún canh đặc sản Ninh Bình với sợi bún to đặc trưng. Nước dùng đậm đà, ăn kèm tiết, chả, tép khô.',
    noteEn: 'Signature Ninh Binh bun canh with extra-large noodles. Rich broth, served with blood cake and dried shrimp.',
  },
  {
    name: 'Bánh Tráng Trộn Phố 8',
    nameEn: 'Pho 8 Rice Paper Salad',
    lat: 20.2570, lng: 105.9710,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Phố 8, khu vực Cù Chính Lan / Lương Văn Tụy, Ninh Bình',
    locationEn: 'Pho 8 area, Cu Chinh Lan / Luong Van Tuy, Ninh Binh',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Bánh tráng trộn gia vị riêng, giòn dai cay thanh. Món ăn vặt "quốc dân" của người Ninh Bình.',
    noteEn: 'Signature rice paper salad with unique seasoning. A beloved local snack.',
  },
];
