// ============================================================
// NINH BÌNH AI — Ăn vặt
// File: anvat.js
//
// Hướng dẫn thêm địa điểm mới:
// - Tọa độ lat/lng: Google Maps → click chuột phải → Sao chép tọa độ
// - priority: true → AI chủ động gợi ý khi tư vấn ăn vặt
// - priority: false → Chỉ hiển thị trên bản đồ
// - type: 'snack' → Ăn vặt / street food (màu hồng #ec4899)
// ============================================================

const SNACKS = [
  {
    name: 'Kem Xôi Thanh Hằng',
    nameEn: 'Thanh Hang Sticky Rice Ice Cream',
    lat: 20.2572,
    lng: 105.9705,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: '36 Cù Chính Lan (Phố 8), Tân Thành, Ninh Bình',
    locationEn: '36 Cu Chinh Lan (Pho 8), Tan Thanh, Ninh Binh',
    price: '15.000 – 40.000đ/cốc',
    priceEn: '15,000 – 40,000 VND/cup',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn vặt kinh điển và nổi tiếng nhất Ninh Bình. Kem xôi dẻo thơm, kem béo ngậy, thường ăn kèm bánh đa giòn. Luôn đông khách từ sáng đến tối muộn.',
    noteEn: 'The most legendary sticky rice ice cream in Ninh Binh. Creamy, fragrant and addictive. Often paired with crispy rice crackers.',
  },
  {
    name: 'Thịt Xiên Nướng Đức Trọc',
    nameEn: 'Duc Troc Grilled Skewers',
    lat: 20.2605,
    lng: 105.9750,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: '52 Hoàng Hoa Thám, Vân Giang, TP. Ninh Bình',
    locationEn: '52 Hoang Hoa Tham Street, Van Giang, Ninh Binh City',
    price: '5.000 – 20.000đ/xiên',
    priceEn: '5,000 – 20,000 VND/skewer',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Thịt xiên nướng nổi tiếng giới trẻ Ninh Bình. Thịt ướp đậm đà, nướng thơm lừng. Giá rẻ, ăn vặt rất hợp. Có cả chân gà, cánh gà, sườn sụn...',
    noteEn: 'Popular grilled skewers loved by local youth. Well-marinated meat, fragrant and affordable. Great for snacking.',
  },
  {
    name: 'Chè Bưởi An Giang',
    nameEn: 'An Giang Grapefruit Sweet Soup',
    lat: 20.2560,
    lng: 105.9720,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: '14 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: '14 Luong Van Tuy Street, Tan Thanh, Ninh Binh',
    price: '15.000 – 25.000đ',
    priceEn: '15,000 – 25,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Chè bưởi chuẩn vị miền Tây, cùi bưởi giòn, đậu xanh mềm, nước cốt dừa béo ngậy. Món ăn vặt mát lạnh được nhiều người khen ngon nhất Ninh Bình.',
    noteEn: 'Authentic Southern-style grapefruit sweet soup with crunchy pomelo, soft mung beans and rich coconut milk. Highly recommended.',
  },
  {
    name: 'Bánh Mì Cố Đô',
    nameEn: 'Co Do Banh Mi',
    lat: 20.2555,
    lng: 105.9725,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: '117 Lương Văn Tụy, Hoa Lư, Ninh Bình',
    locationEn: '117 Luong Van Tuy Street, Hoa Lu, Ninh Binh',
    price: '20.000 – 35.000đ/ổ',
    priceEn: '20,000 – 35,000 VND',
    bestTime: 'Tối',
    bestTimeEn: 'Evening',
    note: 'Bánh mì nóng giòn, nhân đầy ú ụ. Có chương trình tặng nước đậu miễn phí. Được giới trẻ và du khách yêu thích.',
    noteEn: 'Crispy hot baguette with generous fillings. Often offers free soy milk. Popular among locals and tourists.',
  },
  {
    name: 'Bánh Mì Sài Gòn Anh Béo',
    nameEn: 'Anh Beo Saigon Banh Mi',
    lat: 20.2610,
    lng: 105.9760,
    color: '#ec4899',
    type: 'snack',
    priority: false,
    location: '136 Hoàng Diệu, Thanh Bình, TP. Ninh Bình',
    locationEn: '136 Hoang Dieu Street, Thanh Binh, Ninh Binh City',
    price: '20.000 – 30.000đ/ổ',
    priceEn: '20,000 – 30,000 VND',
    bestTime: 'Cả ngày',
    bestTimeEn: 'All day',
    note: 'Bánh mì Sài Gòn chuẩn vị, pate béo ngậy, thịt nướng thơm. Quán quen thuộc của người dân địa phương.',
    noteEn: 'Classic Saigon-style banh mi with rich pate and fragrant grilled meat.',
  },
  {
    name: 'Chè Ngon Phố Vịt',
    nameEn: 'Che Ngon Pho Vit',
    lat: 20.2585,
    lng: 105.9730,
    color: '#ec4899',
    type: 'snack',
    priority: false,
    location: '17 Đinh Tiên Hoàng (Phố Vịt), Đông Thành, Ninh Bình',
    locationEn: '17 Dinh Tien Hoang (Pho Vit), Dong Thanh, Ninh Binh',
    price: '15.000 – 40.000đ',
    priceEn: '15,000 – 40,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Menu chè đa dạng, ngon và mát (chè bưởi, dừa dầm, thập cẩm…). Không gian thoáng, được nhiều bạn trẻ ghé thường xuyên.',
    noteEn: 'Variety of delicious and refreshing sweet soups. Spacious and popular among youth.',
  },
  {
    name: 'Nem Nướng Nha Trang',
    nameEn: 'Nha Trang Grilled Spring Rolls',
    lat: 20.2630,
    lng: 105.9685,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: 'Công viên Thúy Sơn, đường Lê Đại Hành, TP. Ninh Bình',
    locationEn: 'Thuy Son Park, Le Dai Hanh Street, Ninh Binh City',
    price: '40.000 – 80.000đ/phần',
    priceEn: '40,000 – 80,000 VND/serving',
    bestTime: 'Tối',
    bestTimeEn: 'Evening',
    note: 'Nem nướng kiểu Nha Trang, ăn kèm rau sống, bánh tráng, nước chấm đặc trưng. Không gian công viên thoáng mát, rất hợp ăn tối.',
    noteEn: 'Nha Trang-style grilled spring rolls served with fresh herbs, rice paper and signature dipping sauce. Nice park atmosphere.',
  },
  {
    name: 'Bánh Rán Phố Cổ',
    nameEn: 'Old Quarter Fried Pancakes',
    lat: 20.2492,
    lng: 105.9772,
    color: '#ec4899',
    type: 'snack',
    priority: true,
    location: 'Khu ẩm thực đường phố Phố cổ Hoa Lư',
    locationEn: 'Street Food Area, Hoa Lu Old Quarter',
    price: '5.000 – 15.000đ/chiếc',
    priceEn: '5,000 – 15,000 VND/piece',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Bánh rán nóng giòn tan, ăn kèm nước mắm chua ngọt. Món ăn vặt không thể bỏ qua khi dạo Phố cổ về đêm.',
    noteEn: 'Crispy hot fried pancakes with sweet and sour dipping sauce. Must-try street snack in the Old Quarter.',
  },
  {
    name: 'Thịt Xiên Nướng Phố Cổ',
    nameEn: 'Old Quarter Grilled Skewers',
    lat: 20.2490,
    lng: 105.9775,
    color: '#ec4899',
    type: 'snack',
    priority: false,
    location: 'Dãy gian hàng ẩm thực Phố cổ Hoa Lư',
    locationEn: 'Food Stall Row, Hoa Lu Old Quarter',
    price: '10.000 – 25.000đ/xiên',
    priceEn: '10,000 – 25,000 VND/skewer',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Thịt nướng thơm phức, vừa đi vừa ăn. Mùi hương lan tỏa khắp phố cổ.',
    noteEn: 'Fragrant grilled meat skewers. Perfect for walking and snacking.',
  },
  {
    name: 'Bánh Tráng Trộn Phố 8',
    nameEn: 'Pho 8 Rice Paper Salad',
    lat: 20.2570,
    lng: 105.9710,
    color: '#ec4899',
    type: 'snack',
    priority: false,
    location: 'Phố 8 (khu vực Cù Chính Lan / Lương Văn Tụy), Ninh Bình',
    locationEn: 'Pho 8 area (Cu Chinh Lan / Luong Van Tuy), Ninh Binh',
    price: '15.000 – 35.000đ',
    priceEn: '15,000 – 35,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Bánh tráng trộn đặc trưng Ninh Bình, gia vị riêng, giòn dai cay thanh. Món ăn vặt “quốc dân”.',
    noteEn: 'Signature Ninh Binh rice paper salad with unique seasoning. A beloved local snack.',
  }
];
