// ============================================================
//  NINH BÌNH AI — Ăn vặt
//  File: anvat.js
// ============================================================

const SNACKS = [
  {
    name: 'Kem Xôi Thanh Hằng',
    nameEn: 'Thanh Hang Sticky Rice Ice Cream',
    lat: 20.2572, lng: 105.9705,
    color: '#ec4899', type: 'snack', priority: true,
    location: '36 Cù Chính Lan (Phố 8), Tân Thành, Ninh Bình',
    locationEn: '36 Cu Chinh Lan (Pho 8), Tan Thanh, Ninh Binh',
    price: '15.000 – 40.000đ/cốc', priceEn: '15,000 – 40,000 VND/cup',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn vặt kinh điển và nổi tiếng nhất Ninh Bình. Kem xôi dẻo thơm, kem béo ngậy, thường ăn kèm bánh đa giòn. Luôn đông khách từ sáng đến tối muộn.',
    noteEn: 'The most legendary sticky rice ice cream in Ninh Binh. Creamy, fragrant and addictive. Often paired with crispy rice crackers.',
  },
  {
    name: 'Thịt Xiên Nướng Đức Trọc',
    nameEn: 'Duc Troc Grilled Skewers',
    lat: 20.2605, lng: 105.9750,
    color: '#ec4899', type: 'snack', priority: true,
    location: '52 Hoàng Hoa Thám, Vân Giang, TP. Ninh Bình',
    locationEn: '52 Hoang Hoa Tham Street, Van Giang, Ninh Binh City',
    price: '5.000 – 20.000đ/xiên', priceEn: '5,000 – 20,000 VND/skewer',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thịt xiên nướng nổi tiếng giới trẻ Ninh Bình. Thịt ướp đậm đà, nướng thơm lừng. Giá rẻ, ăn vặt rất hợp.',
    noteEn: 'Popular grilled skewers loved by local youth. Well-marinated meat, fragrant and affordable.',
  },
  {
    name: 'Chè Bưởi An Giang',
    nameEn: 'An Giang Grapefruit Sweet Soup',
    lat: 20.2560, lng: 105.9720,
    color: '#ec4899', type: 'snack', priority: true,
    location: '14 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: '14 Luong Van Tuy Street, Tan Thanh, Ninh Binh',
    price: '15.000 – 25.000đ', priceEn: '15,000 – 25,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Chè bưởi chuẩn vị, cùi bưởi giòn, đậu xanh mềm, nước cốt dừa béo ngậy. Món ăn vặt mát lạnh được khen ngon nhất Ninh Bình.',
    noteEn: 'Grapefruit sweet soup with crunchy pomelo, soft mung beans and rich coconut milk. Highly recommended.',
  },
  {
    name: 'Bánh Mì Cố Đô',
    nameEn: 'Co Do Banh Mi',
    lat: 20.2555, lng: 105.9725,
    color: '#ec4899', type: 'snack', priority: true,
    location: '117 Lương Văn Tụy, Hoa Lư, Ninh Bình',
    locationEn: '117 Luong Van Tuy Street, Hoa Lu, Ninh Binh',
    price: '20.000 – 35.000đ/ổ', priceEn: '20,000 – 35,000 VND',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Bánh mì nóng giòn, nhân đầy ú ụ. Có chương trình tặng nước đậu miễn phí. Được giới trẻ và du khách yêu thích.',
    noteEn: 'Crispy hot baguette with generous fillings. Often offers free soy milk. Popular among locals and tourists.',
  },
  {
    name: 'Bánh Mì Chảo Bánh Mì Giòn',
    nameEn: 'Banh Mi Chao - Banh Mi Gion',
    lat: 20.2568, lng: 105.9728,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Số 7, Ngõ 43 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 7, Alley 43 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '15.000 – 45.000đ', priceEn: '15,000 – 45,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh mì chảo nóng giòn nổi tiếng đường Lương Văn Tụy. Ăn kèm pate, trứng, xúc xích, chả... rất hợp ăn sáng hoặc ăn vặt muộn.',
    noteEn: 'Famous hot crispy pan-fried banh mi. Served with pate, egg, sausage, etc. Great for breakfast or late-night snack.',
  },
  {
    name: 'Nem Nướng Nha Trang',
    nameEn: 'Nha Trang Grilled Spring Rolls',
    lat: 20.2630, lng: 105.9685,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Công viên Thúy Sơn, đường Lê Đại Hành, TP. Ninh Bình',
    locationEn: 'Thuy Son Park, Le Dai Hanh Street, Ninh Binh City',
    price: '40.000 – 80.000đ/phần', priceEn: '40,000 – 80,000 VND/serving',
    bestTime: 'Tối', bestTimeEn: 'Evening',
    note: 'Nem nướng kiểu Nha Trang, ăn kèm rau sống, bánh tráng, nước chấm đặc trưng. Không gian công viên thoáng mát.',
    noteEn: 'Nha Trang-style grilled spring rolls with fresh herbs, rice paper and signature dipping sauce. Nice park atmosphere.',
  },
  {
    name: 'Bánh Rán Phố Cổ',
    nameEn: 'Old Quarter Fried Pancakes',
    lat: 20.2492, lng: 105.9772,
    color: '#ec4899', type: 'snack', priority: true,
    location: 'Khu ẩm thực đường phố Phố cổ Hoa Lư',
    locationEn: 'Street Food Area, Hoa Lu Old Quarter',
    price: '5.000 – 15.000đ/chiếc', priceEn: '5,000 – 15,000 VND/piece',
    bestTime: 'Buổi tối', bestTimeEn: 'Evening',
    note: 'Bánh rán nóng giòn tan, ăn kèm nước mắm chua ngọt. Món ăn vặt không thể bỏ qua khi dạo Phố cổ về đêm.',
    noteEn: 'Crispy hot fried pancakes with sweet and sour dipping sauce. Must-try street snack in the Old Quarter at night.',
  },
  {
    name: 'Bún Canh Cu Tý',
    nameEn: 'Bun Canh Cu Ty',
    lat: 20.2565, lng: 105.9722,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 8, Ngõ 75 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 8, Alley 75 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '20.000 – 40.000đ/bát', priceEn: '20,000 – 40,000 VND/bowl',
    bestTime: 'Sáng & Trưa', bestTimeEn: 'Morning & Lunch',
    note: 'Bún canh đặc sản Ninh Bình với sợi bún to đặc trưng. Nước dùng đậm đà, ăn kèm tiết, chả, tép khô.',
    noteEn: 'Signature Ninh Binh bun canh with extra-large noodles. Rich broth, served with blood cake and dried shrimp.',
  },
  {
    name: 'Bánh Tráng Trộn Phố 8',
    nameEn: 'Pho 8 Rice Paper Salad',
    lat: 20.2570, lng: 105.9710,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Phố 8, khu vực Cù Chính Lan / Lương Văn Tụy, Ninh Bình',
    locationEn: 'Pho 8 area, Cu Chinh Lan / Luong Van Tuy, Ninh Binh',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Bánh tráng trộn gia vị riêng, giòn dai cay thanh. Món ăn vặt "quốc dân" của người Ninh Bình.',
    noteEn: 'Signature rice paper salad with unique seasoning. A beloved local snack.',
  },
  {
    name: 'PIZZA SEN NINH BÌNH',
    nameEn: 'Pizza Sen Ninh Binh',
    lat: 20.2633694, lng: 105.9677525,
    color: '#f97316', type: 'western', priority: true,
    location: 'Số 1 Đường Trần Hưng Đạo, Phường Hoa Lư, TP. Ninh Bình (Khu vực Phố cổ Hoa Lư)',
    locationEn: 'No. 1 Tran Hung Dao Street, Hoa Lu Ward, Ninh Binh City (Hoa Lu Old Quarter Area)',
    price: '80.000 – 250.000đ', priceEn: '80,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nằm ngay trong không gian Phố cổ Hoa Lư, quán có không gian đẹp, ấm cúng. Pizza đế giòn thơm, nhiều topping, rất được lòng thực khách và khách du lịch về đêm.',
    noteEn: 'Located right inside Hoa Lu Old Quarter. Cozy atmosphere with crispy-crust pizzas and generous toppings. Highly popular among tourists.',
  },
  {
    name: 'Viva Mexico - Taco & Grill',
    nameEn: 'Viva Mexico - Taco & Grill',
    lat: 20.2651322, lng: 105.9651667,
    color: '#f97316', type: 'western', priority: true,
    location: '26 Ngõ 8 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: '26 Alley 8 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '50.000 – 300.000đ', priceEn: '50,000 – 300,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán chuyên đồ ăn Mexico độc đáo hiếm có tại Ninh Bình với các món Tacos, Burritos, Quesadillas chuẩn vị. Không gian nhỏ nhắn, decor chất và dịch vụ rất thân thiện.',
    noteEn: 'An authentic Mexican restaurant in Ninh Binh serving delicious Tacos, Burritos, and Quesadillas. Charming atmosphere with excellent service.',
  },
  {
    name: 'Pyzzi Pizza Restaurant',
    nameEn: 'Pyzzi Pizza Restaurant',
    lat: 20.2568667, lng: 105.9709161,
    color: '#f97316', type: 'western', priority: false,
    location: '30 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '30 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '40.000 – 200.000đ', priceEn: '40,000 – 200,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Quán pizza quen thuộc với giới trẻ và các gia đình tại trục đường ăn uống Lương Văn Tụy. Phục vụ nhanh chóng, menu đa dạng từ pizza, mỳ Ý đến các món gà rán.',
    noteEn: 'A familiar pizza spot for locals on the lively Luong Van Tuy street. Fast service with a diverse menu including pizza, pasta, and fried chicken.',
  },
  {
    name: 'Pizza Đạt Italy Bar & Restaurant',
    nameEn: 'Pizza Dat Italy Bar & Restaurant',
    lat: 20.2475881, lng: 105.9330287,
    color: '#f97316', type: 'western', priority: true,
    location: 'Thôn Khê Hạ, Xã Ninh Xuân, Huyện Hoa Lư, Ninh Bình',
    locationEn: 'Khe Ha Hamlet, Ninh Xuan Communce, Hoa Lu District, Ninh Binh',
    price: '100.000 – 250.000đ', priceEn: '100,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nằm gần khu vực các điểm du lịch sinh thái, quán được đánh giá cực cao (4.9 sao) bởi du khách nước ngoài nhờ hương vị Pizza, Mỳ Ý thuần túy chuẩn vị Âu và chủ quán cực kỳ hiếu khách.',
    noteEn: 'Highly rated restaurant near tourist hubs, praised by foreigners for authentic Italian pizzas, pasta, steaks and super welcoming hospitality.',
  },
  {
    name: 'D.Cafe&Bistro - Wood Fired Pizza & Steak',
    nameEn: 'D.Cafe&Bistro - Wood Fired Pizza & Steak',
    lat: 20.2596956, lng: 105.9635048,
    color: '#f97316', type: 'western', priority: true,
    location: '168 Xuân Thành, Phường Tân Thành, TP. Ninh Bình',
    locationEn: '168 Xuan Thanh Street, Tan Thanh Ward, Ninh Binh City',
    price: '60.000 – 350.000đ', priceEn: '60,000 – 350,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Nổi tiếng với dòng Pizza nướng lò củi truyền thống mang lại lớp vỏ giòn rụm và mùi thơm đặc trưng mộc mạc. Không gian kiểu bistro hiện đại, sang trọng thích hợp hẹn hò hoặc tụ họp gia đình.',
    noteEn: 'Famous for authentic wood-fired pizzas with a smoky fragrance and crispy crust. Elegant modern bistro space perfect for dates and family gatherings.',
  },
  {
    name: 'Chả cá Hà Thành',
    nameEn: 'Ha Thanh Grilled Fish',
    lat: 20.259852, lng: 105.969841,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 9 Cù Chính Lan, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 9 Cu Chinh Lan Street, Tan Thanh, Ninh Binh City',
    price: '120.000 – 200.000đ/người', priceEn: '120,000 – 200,000 VND/pax',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chả cá lăng nướng thơm phức trên chảo nóng kèm hành, thì là, ăn với bún và mắm tôm chuẩn vị Hà Nội.',
    noteEn: 'Grilled hemibagrus fish served with dill, spring onions, rice noodles, and shrimp paste.',
  },
  {
    name: 'Choose Hideaway Restaurant',
    nameEn: 'Choose Hideaway Restaurant',
    lat: 20.252433, lng: 105.938501,
    color: '#f97316', type: 'western', priority: true,
    location: 'Thôn Đam Khê Trong, Xã Ninh Hải, Hoa Lư, Ninh Bình',
    locationEn: 'Dam Khe Trong Hamlet, Ninh Hai Commune, Hoa Lu, Ninh Binh',
    price: '80.000 – 250.000đ', priceEn: '80,000 – 250,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Không gian nhà hàng ẩn mình cực chill gần Tam Cốc, nổi tiếng với Pizza, Burgers và các món Âu được khách quốc tế đánh giá rất cao.',
    noteEn: 'A cozy hidden gem near Tam Coc, famous for western dishes, pizzas, and burgers.',
  },
  {
    name: 'Heemang Chicken',
    nameEn: 'Heemang Chicken',
    lat: 20.261895, lng: 105.961314,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Số 10 Ngõ 6 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 10, Alley 6 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '50.000 – 180.000đ', priceEn: '50,000 – 180,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán gà rán và đồ ăn vặt kiểu Hàn Quốc nằm ngay đoạn đầu ngõ vào Tràng An, không gian trẻ trung.',
    noteEn: 'Korean fried chicken and street food shop near Trang An street.',
  },
  {
    name: 'Gà rán Chaewon Trịnh Thị Trang',
    nameEn: 'Chaewon Korean Fried Chicken',
    lat: 20.253341, lng: 105.975412,
    color: '#ef4444', type: 'asian', priority: false,
    location: '46 Tuệ Tĩnh, Phường Nam Thành, TP. Ninh Bình',
    locationEn: '46 Tue Tinh Street, Nam Thanh Ward, Ninh Binh City',
    price: '30.000 – 150.000đ', priceEn: '30,000 – 150,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Thương hiệu gà rán sốt Hàn Quốc quen thuộc của học sinh sinh viên khu vực Nam Thành.',
    noteEn: 'Popular Korean-style sauced fried chicken spot among local students.',
  },
  {
    name: 'Busan Ninh Bình',
    nameEn: 'Busan Korean Food Ninh Binh',
    lat: 20.256158, lng: 105.973415,
    color: '#ef4444', type: 'asian', priority: true,
    location: '06 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '06 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '40.000 – 150.000đ', priceEn: '40,000 – 150,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuyên các món ăn đường phố Hàn Quốc như lẩu tokbokki, cơm trộn, mì tương đen ngay trung tâm phố ăn vặt.',
    noteEn: 'Specializing in Korean street food like tokbokki hotpot, bibimbap, and jiajangmyeon.',
  },
  {
    name: 'Blur Chicken',
    nameEn: 'Blur Chicken',
    lat: 20.255912, lng: 105.972104,
    color: '#f97316', type: 'western', priority: false,
    location: 'Ngõ 43 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Alley 43 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '30.000 – 120.000đ', priceEn: '30,000 – 120,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn nhanh chuyên gà rán khoai tây chiên, không gian phù hợp cho nhóm bạn trẻ tụ tập.',
    noteEn: 'Fast food spot focusing on fried chicken and french fries.',
  },
  {
    name: 'KFC Ninh Bình',
    nameEn: 'KFC Ninh Binh',
    lat: 20.252874, lng: 105.974852,
    color: '#f97316', type: 'western', priority: false,
    location: 'Tầng 1 Trung tâm Thương mại Go! Ninh Bình, Đường Trần Nhân Tông, TP. Ninh Bình',
    locationEn: '1st Floor, Go! Mall, Tran Nhan Tong Street, Ninh Binh City',
    price: '40.000 – 150.000đ', priceEn: '40,000 – 150,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Cửa hàng gà rán thức ăn nhanh quốc tế nằm bên trong siêu thị Go! Ninh Bình.',
    noteEn: 'International fast-food chain located inside Go! Mall Ninh Binh.',
  },
  {
    name: 'Jollibee Ninh Bình Trần Hưng Đạo',
    nameEn: 'Jollibee Tran Hung Dao',
    lat: 20.256581, lng: 105.980144,
    color: '#f97316', type: 'western', priority: false,
    location: '02 Trần Hưng Đạo, Phường Đông Thành, TP. Ninh Bình',
    locationEn: '02 Tran Hung Dao Street, Dong Thanh Ward, Ninh Binh City',
    price: '30.000 – 100.000đ', priceEn: '30,000 – 100,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Thương hiệu gà rán, mỳ Ý nổi tiếng phù hợp cho gia đình có trẻ nhỏ, nằm ngay trục đường lớn.',
    noteEn: 'Famous fried chicken and spaghetti fast-food chain, family-friendly.',
  },
  {
    name: 'Ăn vặt bé mỡ (통통이 분식)',
    nameEn: 'Be Mo Korean Snack',
    lat: 20.260451, lng: 105.962115,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Số 33 Ngõ 1 Đường Tràng An, Tân Thành, TP. Ninh Bình',
    locationEn: 'No. 33, Alley 1 Trang An Street, Tan Thanh, Ninh Binh City',
    price: '20.000 – 80.000đ', priceEn: '20,000 – 80,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Tiệm ăn vặt nhỏ xinh chuyên các món Hàn tự làm chuẩn vị, giá cả rất học sinh sinh viên.',
    noteEn: 'Charming small eatery serving homemade Korean street food at budget-friendly prices.',
  },
  {
    name: 'Nhà Hàng Hàn Quốc Hong Kang (중화요리 홍강)',
    nameEn: 'Hong Kang Korean Chinese Restaurant',
    lat: 20.259924, lng: 105.966412,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Phố Tân Trung, Đường Lê Thái Tổ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Tan Trung Area, Le Thai To Street, Tan Thanh, Ninh Binh City',
    price: '100.000 – 300.000đ', priceEn: '100,000 – 300,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Nhà hàng chuyên ẩm thực Trung - Hàn (mì tương đen, mì cay hải sản jjamppong, thịt heo chua ngọt탕수육) chuẩn vị do đầu bếp kinh nghiệm chế biến.',
    noteEn: 'Authentic Korean-Chinese restaurant serving Jjajangmyeon, Jjamppong, and Tangsuyuk.',
  },
  {
    name: 'Wallace Ninh Bình',
    nameEn: 'Wallace Burger & Chicken',
    lat: 20.255104, lng: 105.972901,
    color: '#f97316', type: 'western', priority: false,
    location: '136 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '136 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '25.000 – 80.000đ', priceEn: '25,000 – 80,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Thương hiệu đồ ăn nhanh chuyên các dòng hamburger giá rẻ và gà rán giòn rụm.',
    noteEn: 'Fast-food chain specialized in budget-friendly burgers and crispy fried chicken.',
  },
  {
    name: 'Hàn Quốc Quán Ninh Bình (한국관)',
    nameEn: 'Han Quoc Quan Restaurant',
    lat: 20.258752, lng: 105.966814,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Đường Lê Thái Tổ, Phường Tân Thành, TP. Ninh Bình',
    locationEn: 'Le Thai To Street, Tan Thanh Ward, Ninh Binh City',
    price: '150.000 – 350.000đ', priceEn: '150,000 – 350,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Một trong những nhà hàng đồ nướng và lẩu Hàn Quốc lâu đời, phục vụ đúng phong cách bản xứ với nhiều panchan đi kèm.',
    noteEn: 'Traditional Korean BBQ and hotpot restaurant with authentic flavors and side dishes.',
  },
  {
    name: 'Nhà Hàng Trung Hoa Tương Vận Các',
    nameEn: 'Tuong Van Cac Chinese Restaurant',
    lat: 20.266245, lng: 105.968112,
    color: '#ef4444', type: 'asian', priority: true,
    location: 'Đường Tràng An, Phường Hoa Lư, TP. Ninh Bình (Gần khu Phố Cổ)',
    locationEn: 'Trang An Street, Hoa Lu Ward, Ninh Binh City',
    price: '100.000 – 400.000đ', priceEn: '100,000 – 400,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Chuyên đồ ăn Trung Hoa đại lục, các món vịt quay, sủi cảo, đậu sốt Tứ Xuyên đậm đà.',
    noteEn: 'Authentic Chinese restaurant featuring roasted duck, dumplings, and Sichuan tofu.',
  },
  {
    name: 'Bánh Mì Giòn',
    nameEn: 'Banh Mi Gion',
    lat: 20.256801, lng: 105.972822,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Số 7, Ngõ 43 Lương Văn Tụy, Tân Thành, Ninh Bình',
    locationEn: 'No. 7, Alley 43 Luong Van Tuy, Tan Thanh, Ninh Binh',
    price: '15.000 – 45.000đ', priceEn: '15,000 – 45,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Cơ sở chuyên bánh mì chảo và bánh mì kẹp giòn nóng hổi phục vụ ăn sáng hoặc ăn muộn.',
    noteEn: 'Specializing in crispy baguettes and pan-fried banh mi for breakfast or late snacks.',
  },
  {
    name: 'Bánh mỳ Ngọc',
    nameEn: 'Ngoc Banh Mi',
    lat: 20.258954, lng: 105.974102,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Vân Giang, Phường Vân Giang, TP. Ninh Bình',
    locationEn: 'Van Giang Street, Van Giang Ward, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Sáng & Chiều', bestTimeEn: 'Morning & Afternoon',
    note: 'Hàng bánh mì patê truyền thống lâu đời, nước sốt đậm đà, vỏ bánh luôn được nướng nóng giòn trước khi giao.',
    noteEn: 'Long-standing traditional pate banh mi with rich signature sauce.',
  },
  {
    name: 'Bánh Mỳ Đò Quan NĐ - Buffet Xiên',
    nameEn: 'Do Quan Banh Mi & Skewer Buffet',
    lat: 20.251452, lng: 105.976822,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần cầu Đò Quan (Khu vực Nam Thành / Vân Giang), TP. Ninh Bình',
    locationEn: 'Near Do Quan bridge area, Ninh Binh City',
    price: '20.000 – 60.000đ', priceEn: '20,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Nổi tiếng với món bánh mì kiểu Nam Định kết hợp quầy buffet xiên bẩn, xiên nướng tự chọn thu hút giới trẻ.',
    noteEn: 'Nam Dinh style banh mi combined with an active self-select skewer buffet.',
  },
  {
    name: 'Bánh mì bơ house',
    nameEn: 'Bo House Banh Mi',
    lat: 20.254821, lng: 105.971552,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Nguyễn Văn Cừ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Nguyen Van Cu Street, Tan Thanh, Ninh Binh City',
    price: '15.000 – 35.000đ', priceEn: '15,000 – 35,000 VND',
    bestTime: 'Sáng & Chiều', bestTimeEn: 'Morning & Afternoon',
    note: 'Tiệm bánh mì hiện đại với các loại nhân đa dạng, đặc biệt là sốt bơ trứng gà tươi tự làm béo ngậy.',
    noteEn: 'Modern banh mi shop featuring rich, creamy homemade egg-butter sauce.',
  },
  {
    name: 'Bánh Mì Siu Bơ',
    nameEn: 'Siu Bo Banh Mi',
    lat: 20.255412, lng: 105.972105,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Trục đường Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: 'Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '15.000 – 30.000đ', priceEn: '15,000 – 30,000 VND',
    bestTime: 'Cả ngày', bestTimeEn: 'All day',
    note: 'Điểm bán bánh mì giòn rụm với bơ siêu thơm, thích hợp mua mang đi nhanh chóng.',
    noteEn: 'Quick takeaway spot for crispy banh mi with aromatic butter.',
  },
  {
    name: 'Tiệm Bánh Mỳ Hùng',
    nameEn: 'Hung Banh Mi',
    lat: 20.258122, lng: 105.976104,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Đường Lê Hồng Phong, Đông Thành, TP. Ninh Bình',
    locationEn: 'Le Hong Phong Street, Dong Thanh, Ninh Binh City',
    price: '20.000 – 40.000đ', priceEn: '20,000 – 40,000 VND',
    bestTime: 'Sáng & Tối', bestTimeEn: 'Morning & Evening',
    note: 'Bánh mì thịt nguội, xá xíu truyền thống đầy đặn, phục vụ nhanh nhẹn.',
    noteEn: 'Traditional banh mi filled with char siu pork and cold cuts.',
  },
  {
    name: 'Bi Quán - Đặc sản Đà Nẵng',
    nameEn: 'Bi Quan - Da Nang Specialties',
    lat: 20.257541, lng: 105.971254,
    color: '#ef4444', type: 'asian', priority: false,
    location: 'Phố 8, Tân Thành, TP. Ninh Bình',
    locationEn: 'Pho 8, Tan Thanh, Ninh Binh City',
    price: '30.000 – 70.000đ', priceEn: '30,000 – 70,000 VND',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Mang hương vị miền Trung ra đất cố đô với bánh xèo giòn rụm, nem lụi nướng sả và bún mắm nêm đậm đà.',
    noteEn: 'Serving central Vietnam flavors including crispy Banh Xeo and savory Nem Lui.',
  },
  {
    name: 'Mì Cay SEOUL',
    nameEn: 'Seoul Spicy Noodles',
    lat: 20.255241, lng: 105.973104,
    color: '#ec4899', type: 'snack', priority: true,
    location: '142 Lương Văn Tụy, Tân Thành, TP. Ninh Bình',
    locationEn: '142 Luong Van Tuy Street, Tan Thanh, Ninh Binh City',
    price: '35.000 – 70.000đ', priceEn: '35,000 – 70,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Hệ thống mì cay 7 cấp độ nổi tiếng, luôn tấp nập học sinh sinh viên vào buổi tối. Mì nhiều topping hải sản, bò, kim chi.',
    noteEn: 'Famous 7-level Korean spicy noodle soup restaurant, popular with youth.',
  },
  {
    name: 'Bít Tết A Sấm',
    nameEn: 'A Sam Beefsteak',
    lat: 20.259124, lng: 105.968841,
    color: '#f97316', type: 'western', priority: false,
    location: 'Đường Nguyễn Huệ, Phường Nam Bình, TP. Ninh Bình',
    locationEn: 'Nguyen Hue Street, Nam Binh Ward, Ninh Binh City',
    price: '60.000 – 120.000đ/suất', priceEn: '60,000 – 120,000 VND/serving',
    bestTime: 'Trưa & Tối', bestTimeEn: 'Lunch & Evening',
    note: 'Bít tết chảo gang nóng hổi kiểu Việt Nam ăn kèm khoai tây chiên, trứng ốp la và bánh mì giòn.',
    noteEn: 'Vietnamese-style sizzling beefsteak served with fries, fried egg, and baguette.',
  },
  {
    name: 'Ăn Vặt Win Win',
    nameEn: 'Win Win Snack Shop',
    lat: 20.254102, lng: 105.971945,
    color: '#ec4899', type: 'snack', priority: false,
    location: 'Gần trường THPT Chuyên Lương Văn Tụy cũ, Tân Thành, TP. Ninh Bình',
    locationEn: 'Near old Luong Van Tuy High School, Tan Thanh, Ninh Binh City',
    price: '15.000 – 50.000đ', priceEn: '15,000 – 50,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Thiên đường ăn vặt với đầy đủ trà sữa, nem chua rán, phô mai que và chân gà sả ớt.',
    noteEn: 'Snack paradise featuring milk tea, fried fermented pork rolls, and cheese sticks.',
  },
  {
    name: 'Bánh tacos nhà labubu',
    nameEn: 'Labubu Tacos House',
    lat: 20.260114, lng: 105.965412,
    color: '#f97316', type: 'western', priority: false,
    location: 'Khu vực Đền Đô / Phố Cổ Hoa Lư, TP. Ninh Bình',
    locationEn: 'Hoa Lu Old Quarter Area, Ninh Binh City',
    price: '30.000 – 60.000đ', priceEn: '30,000 – 60,000 VND',
    bestTime: 'Chiều & Tối', bestTimeEn: 'Afternoon & Evening',
    note: 'Quầy đồ ăn bắt trend chuyên phục vụ bánh Tacos vỏ giòn, vỏ mềm với phần nhân biến tấu hợp khẩu vị giới trẻ.',
    noteEn: 'Trendy street-food stall specializing in Mexican tacos adapted to local tastes.',
  },
];
