// ============================================================
//  NINH BÌNH AI — Địa điểm tham quan
//  File: khudiem.js
//
//  Hướng dẫn thêm địa điểm mới:
//  - Tọa độ lat/lng: Google Maps → click chuột phải → Sao chép tọa độ
//  - priority: true  → AI chủ động nhắc đến khi tư vấn
//  - priority: false → Chỉ hiển thị trên bản đồ, AI không chủ động nhắc
//  - color: '#ef4444' (đỏ) cho tất cả điểm tham quan
// ============================================================

const ATTRACTIONS = [
  {
    name: 'Tràng An',
    nameEn: 'Trang An',
    lat: 20.2521, lng: 105.8728,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: '300.000đ/người lớn, 150.000đ/trẻ 1m–1m3, dưới 1m miễn phí',
    ticketEn: '300,000 VND/adult, 150,000/child 1m–1.3m, under 1m free',
    hours: '6h – 16h45',
    note: 'Di sản UNESCO kép — đi thuyền qua hang động, 3 tuyến 2.5–3h. Đặt vé online trước, đến trước 8h tránh đông.',
    noteEn: 'UNESCO dual heritage — boat through caves, 3 routes 2.5–3hrs. Book online, arrive before 8am to avoid crowds.',
  },
  {
    name: 'Hang Múa',
    nameEn: 'Hang Mua',
    lat: 20.2268, lng: 105.9143,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: '150.000đ/người (từ 1m trở lên), dưới 1m miễn phí',
    ticketEn: '150,000 VND/person (over 1m tall), under 1m free',
    hours: '6h – 19h',
    note: 'Leo 486 bậc đá lên đỉnh Ngọa Long, ngắm toàn cảnh Tam Cốc. Đi lúc 6h30 sáng tránh nắng và có ảnh đẹp.',
    noteEn: '486 stone steps to Ngoa Long peak, panoramic Tam Coc view. Go at 6:30am to avoid heat and get great photos.',
  },
  {
    name: 'Tam Cốc',
    nameEn: 'Tam Coc',
    lat: 20.2282, lng: 105.9104,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: '250.000đ/người lớn',
    ticketEn: '250,000 VND/adult',
    hours: '7h – 17h',
    note: 'Đi thuyền qua 3 hang động, ngắm đồng lúa. Đẹp nhất tháng 5–6 lúa chín vàng.',
    noteEn: 'Boat through 3 caves past rice paddies. Most beautiful May–Jun golden rice season.',
  },
  {
    name: 'Cố đô Hoa Lư',
    nameEn: 'Hoa Lu Ancient Capital',
    lat: 20.2803, lng: 105.9057,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: '20.000đ/người lớn, 10.000đ/trẻ 6–15 tuổi, miễn phí trẻ dưới 6 và người trên 60 tuổi',
    ticketEn: '20,000 VND/adult, 10,000/child 6–15, free under 6 & over 60',
    hours: '6h – 18h',
    note: 'Kinh đô cổ thế kỷ X, đền thờ vua Đinh và vua Lê. Ban đêm Phố cổ Hoa Lư có đèn lồng, nhiều quán ăn ngon.',
    noteEn: '10th-century ancient capital, temples of King Dinh and King Le. Hoa Lu Old Quarter has lanterns at night and great food.',
  },
  {
    name: 'Chùa Bái Đính',
    nameEn: 'Bai Dinh Pagoda',
    lat: 20.3527, lng: 105.8708,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: 'Vào cổng miễn phí, xe điện 150.000đ/người',
    ticketEn: 'Free entry, electric cart 150,000 VND/person',
    hours: '6h – 18h',
    note: 'Quần thể chùa lớn nhất Đông Nam Á. Rất rộng, nên đi xe điện.',
    noteEn: 'Largest pagoda complex in Southeast Asia. Very large — take the electric cart.',
  },
  {
    name: 'Đầm Vân Long',
    nameEn: 'Van Long Wetland Reserve',
    lat: 20.3703, lng: 105.8675,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: '150.000đ/người',
    ticketEn: '150,000 VND/person',
    hours: '7h30 – 18h',
    note: 'Khu bảo tồn thiên nhiên ngập nước lớn nhất Bắc Bộ, nơi ngắm voọc quần đùi trắng. Không gian cực kỳ yên bình, ít xô bồ.',
    noteEn: 'Largest wetland reserve in Northern Vietnam, home to Delacour\'s langur. Very peaceful and less touristy.',
  },
  {
    name: 'Vườn quốc gia Cúc Phương',
    nameEn: 'Cuc Phuong National Park',
    lat: 20.3508, lng: 105.6074,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: '60.000đ/người lớn, 10.000đ/trẻ em',
    ticketEn: '60,000 VND/adult, 10,000/child',
    hours: '6h – 22h',
    note: 'Vườn quốc gia đầu tiên của Việt Nam. Nên đi vào tháng 4-5 để ngắm mùa bướm. Có cây chò ngàn năm và trung tâm cứu hộ linh trưởng.',
    noteEn: 'Vietnam\'s first national park. Best visited in Apr-May for butterfly season. Features ancient trees and primate rescue centers.',
  },
  {
    name: 'Động Am Tiên (Tuyệt Tịnh Cốc)',
    nameEn: 'Am Tien Cave',
    lat: 20.2831, lng: 105.9083,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: '100.000đ/người lớn',
    ticketEn: '100,000 VND/adult',
    hours: '7h – 18h',
    note: 'Nằm trong quần thể di tích Hoa Lư, có hồ nước xanh ngắt quanh năm. Thích hợp để check-in sống ảo và tận hưởng không khí tĩnh lặng.',
    noteEn: 'Located within Hoa Lu complex, featuring a year-round turquoise lake. Perfect for photography and enjoying quiet atmosphere.',
  },
  {
    name: 'Khu du lịch sinh thái Thung Nham',
    nameEn: 'Thung Nham Bird Park',
    lat: 20.2078, lng: 105.9220,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: '250.000đ/người lớn',
    ticketEn: '250,000 VND/adult',
    hours: '7h – 18h',
    note: 'Nổi tiếng với vườn chim tự nhiên, Động Vái Giời và Hang Bụt. Nên ghé thăm vườn chim sau 16h để ngắm chim về tổ.',
    noteEn: 'Famous for its natural bird garden, Vai Gioi Cave, and But Cave. Best to visit the bird garden after 4pm.',
  },
  {
    name: 'Chùa Bích Động',
    nameEn: 'Bich Dong Pagoda',
    lat: 20.2177, lng: 105.9147,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: 'Miễn phí tham quan (chỉ mất phí gửi xe khoảng 10k-20k)',
    ticketEn: 'Free entry (parking fee ~10,000-20,000 VND)',
    hours: 'Cả ngày',
    note: 'Được mệnh danh là "Nam thiên đệ nhị động". Chùa cổ nằm tựa vào vách núi với kiến trúc 3 tầng: Hạ, Trung, Thượng.',
    noteEn: 'Known as the "Second best cave in the South". Ancient pagoda built into a cliff with 3 levels: Lower, Middle, and Upper.',
  },
  {
    name: 'Động Thiên Hà',
    nameEn: 'Thien Ha Cave',
    lat: 20.2372, lng: 105.8925,
    color: '#ef4444',
    type: 'attraction',
    priority: false,
    ticket: '120.000đ/người lớn, 60.000đ/trẻ em',
    ticketEn: '120,000 VND/adult, 60,000/child',
    hours: '7h30 – 17h30',
    note: 'Hệ thống hang động thạch nhũ còn nguyên sơ, có cả động khô và động ướt. Được ví như "Dải ngân hà trong lòng núi".',
    noteEn: 'Pristine cave system with both dry and wet sections. Nicknamed the "Galaxy inside the mountain".',
  },
  {
    name: 'Thung Ui',
    nameEn: 'Thung Ui',
    lat: 20.3380, lng: 105.8810,
    color: '#ef4444',
    type: 'attraction',
    priority: true,
    ticket: 'Xe điện 150.000đ/người',
    ticketEn: 'Electric cart 150,000 VND/person',
    hours: '7h – 17h',
    note: 'Hành cung Hoa Lư xưa, không gian hoang sơ ít người biết, văn hóa Mường độc đáo. Gần Bái Đính ~3km.',
    noteEn: 'Former royal retreat, off-the-beaten-path, unique Muong culture. Near Bai Dinh ~3km.',
  },
];
