// ============================================================
//  NINH BÌNH AI — Cơ sở lưu trú
//  File: luutru.js
//
//  Hướng dẫn thêm cơ sở mới:
//  - Tọa độ lat/lng: Google Maps → click chuột phải → Sao chép tọa độ
//  - priority: true  → AI chủ động gợi ý khi tư vấn lưu trú
//  - priority: false → Chỉ hiển thị trên bản đồ
//  - color: '#3b82f6' (xanh dương) cho tất cả cơ sở lưu trú
//  - checkin/checkout: điền đúng giờ thực tế của cơ sở
// ============================================================

const HOTELS = [
  {
    name: 'Legend Hotel',
    nameEn: 'Legend Hotel',
    lat: 20.2526, lng: 105.9735,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.200.000 – 2.500.000đ/đêm',
    priceEn: '1,200,000 – 2,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: '4 sao, 3 hồ bơi, buffet sáng đa dạng, phòng rộng rãi, nhân viên chuyên nghiệp. Lý tưởng cho gia đình và đoàn lớn.',
    noteEn: '4-star, 3 pools, diverse breakfast buffet, spacious rooms, professional staff. Ideal for families and large groups.',
  },
  {
    name: 'The Reed Hotel',
    nameEn: 'The Reed Hotel',
    lat: 20.2525, lng: 105.9745,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.090.000 – 2.000.000đ/đêm',
    priceEn: '1,090,000 – 2,000,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: '4 sao, trung tâm TP Ninh Bình, 153 phòng từ 33m², hồ bơi ngoài trời, spa, nhà hàng buffet, view sông.',
    noteEn: '4-star, city center, 153 rooms from 33m², outdoor pool, spa, buffet restaurant, river view.',
  },
  {
    name: 'Milan Hotel',
    nameEn: 'Milan Hotel',
    lat: 20.2489, lng: 105.9772,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 3,
    price: '700.000 – 1.100.000đ/đêm',
    priceEn: '700,000 – 1,100,000 VND/night (~29–30 USD)',
    checkin: '14h00', checkout: '12h00',
    note: '3 sao, 33 Trần Hưng Đạo, đối diện Phố cổ Hoa Lư, ban công view phố cổ, nhân viên nhiệt tình.',
    noteEn: '3-star, 33 Tran Hung Dao, directly opposite Hoa Lu Old Quarter, balcony with Old Quarter view.',
  },
  {
    name: 'Emeralda Resort Ninh Bình',
    nameEn: 'Emeralda Resort Ninh Binh',
    lat: 20.3601, lng: 105.8824,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 5,
    price: '2.200.000 – 4.500.000đ/đêm',
    priceEn: '2,200,000 – 4,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Resort 5 sao phong cách làng quê Bắc Bộ, nằm gần đầm Vân Long. Không gian yên tĩnh, phòng cực rộng, phù hợp nghỉ dưỡng cao cấp.',
    noteEn: '5-star resort with Northern Vietnamese village style, located near Van Long Reserve. Peaceful, spacious rooms, ideal for luxury retreats.',
  },
  {
    name: 'Tam Coc Garden Resort',
    nameEn: 'Tam Coc Garden Resort',
    lat: 20.2078, lng: 105.9325,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '3.500.000 – 6.000.000đ/đêm',
    priceEn: '3,500,000 – 6,000,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Khu nghỉ dưỡng Boutique cao cấp giữa cánh đồng lúa Tam Cốc. Trải nghiệm xanh, bền vững và cực kỳ riêng tư.',
    noteEn: 'High-end boutique resort set amidst Tam Coc rice fields. Eco-friendly, sustainable, and highly private experience.',
  },
  {
    name: 'Lalita Boutique Hotel & Spa',
    nameEn: 'Lalita Boutique Hotel & Spa',
    lat: 20.2225, lng: 105.9350,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.300.000 – 2.200.000đ/đêm',
    priceEn: '1,300,000 – 2,200,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Phong cách hiện đại pha lẫn nét Á Đông, nằm gần bến thuyền Tam Cốc. Hồ bơi đẹp và dịch vụ spa chuyên nghiệp.',
    noteEn: 'Modern style with Asian touches, located near Tam Coc boat station. Features a beautiful pool and professional spa services.',
  },
  {
    name: 'Tràng An Lamia Bungalow',
    nameEn: 'Trang An Lamia Bungalow',
    lat: 20.2785, lng: 105.9080,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: '800.000 – 1.500.000đ/đêm',
    priceEn: '800,000 – 1,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Bungalow thân thiện với môi trường, thiết kế tre nứa độc đáo. Gần khu du lịch Tràng An, phù hợp cho khách thích gần gũi thiên nhiên.',
    noteEn: 'Eco-friendly bungalows with unique bamboo design. Near Trang An complex, perfect for nature lovers.',
  },
  {
    name: 'Aravinda Resort Ninh Bình',
    nameEn: 'Aravinda Resort Ninh Binh',
    lat: 20.1985, lng: 105.9300,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '2.500.000 – 4.000.000đ/đêm',
    priceEn: '2,500,000 – 4,000,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Nằm tại thung lũng Hải Nham, phong cách tối giản, sang trọng và yên tĩnh tuyệt đối. Đồ ăn organic rất ngon.',
    noteEn: 'Located in Hai Nham valley, minimalist and luxury style with absolute tranquility. Excellent organic food.',
  },
  {
    name: 'Rêu Coffee & Stay',
    nameEn: 'Reu Coffee & Stay',
    lat: 20.2320, lng: 105.9200,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: 'Liên hệ để biết giá',
    priceEn: 'Contact for pricing',
    checkin: '14h00', checkout: '12h00',
    note: 'Không gian xanh mướt độc đáo, vừa là quán cà phê vừa là chỗ nghỉ, check-in cực đẹp. Giới trẻ yêu thích.',
    noteEn: 'Unique lush green space, café and guesthouse combined, very photogenic. Popular with young travelers.',
  },
  {
    name: 'Ninh Binh Hidden Charm Hotel & Resort',
    nameEn: 'Ninh Binh Hidden Charm Hotel & Resort',
    lat: 20.2185, lng: 105.9298,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.800.000 – 3.500.000đ/đêm',
    priceEn: '1,800,000 – 3,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Sát bến thuyền Tam Cốc, thiết kế sang trọng, ấm cúng. Có hồ bơi ngoài trời và câu lạc bộ trẻ em.',
    noteEn: 'Next to Tam Coc wharf, elegant and cozy design. Features an outdoor pool and kids club.',
  },
  {
    name: 'Hang Mua Ecolodge',
    nameEn: 'Hang Mua Ecolodge',
    lat: 20.2285, lng: 105.9180,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: '1.000.000 – 1.800.000đ/đêm',
    priceEn: '1,000,000 – 1,800,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Nằm ngay trong khuôn viên Hang Múa, view nhìn thẳng ra đồng lúa và núi non. Vị trí đắc địa để leo núi sớm.',
    noteEn: 'Located right inside Hang Mua complex, direct view of rice fields and mountains. Prime location for early hiking.',
  },
  {
    name: 'Bái Đính Garden Resort & Spa',
    nameEn: 'Bai Dinh Garden Resort & Spa',
    lat: 20.2760, lng: 105.8650,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.900.000 – 3.200.000đ/đêm',
    priceEn: '1,900,000 – 3,200,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Gần chùa Bái Đính, không gian xanh, yên tĩnh và tinh tế. Dịch vụ spa chuyên sâu và phòng tập gym đầy đủ.',
    noteEn: 'Near Bai Dinh Pagoda, green, quiet, and sophisticated space. Intensive spa services and well-equipped gym.',
  },
  {
    name: 'Hoàng Sơn White Palace',
    nameEn: 'Hoang Son White Palace',
    lat: 20.2450, lng: 105.9800,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '900.000 – 1.600.000đ/đêm',
    priceEn: '900,000 – 1,600,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: '4 sao, trung tâm thành phố, khuôn viên rộng, có bể bơi bốn mùa. Phù hợp cho cả khách công tác và du lịch.',
    noteEn: '4-star, city center, large campus, with a four-season swimming pool. Suitable for both business and leisure travelers.',
  },
  {
    name: 'Tam Coc Rice Fields Resort',
    nameEn: 'Tam Coc Rice Fields Resort',
    lat: 20.2050, lng: 105.9380,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 3,
    price: '850.000 – 1.500.000đ/đêm',
    priceEn: '850,000 – 1,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Bungalow kiểu mái lá nằm giữa cánh đồng, mang lại trải nghiệm làng quê thực thụ. View núi đá vôi cực đẹp.',
    noteEn: 'Thatched-roof bungalows set in the middle of fields, offering a true countryside experience. Stunning limestone views.',
  },
  {
    name: 'Sparrow’s Song Homestay',
    nameEn: 'Sparrow’s Song Homestay',
    lat: 20.2205, lng: 105.9320,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: '600.000 – 950.000đ/đêm',
    priceEn: '600,000 – 950,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Homestay nổi tiếng với sự hiếu khách, hồ bơi sạch sẽ, vị trí yên tĩnh nhưng vẫn gần Tam Cốc.',
    noteEn: 'Well-known homestay for hospitality, clean pool, quiet location but still close to Tam Coc.',
  },
  {
    name: 'Vedana Resort Ninh Bình',
    nameEn: 'Vedana Resort Ninh Binh',
    lat: 20.3160, lng: 105.7050,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 5,
    price: '2.500.000 – 5.500.000đ/đêm',
    priceEn: '2,500,000 – 5,500,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Kiến trúc tre độc đáo nhất Việt Nam, nằm gần rừng Cúc Phương. Không gian khoáng đạt, có hồ khoáng nóng và villa trên mặt nước.',
    noteEn: 'Most unique bamboo architecture in Vietnam, located near Cuc Phuong Forest. Features hot mineral pools and overwater villas.',
  },
  {
    name: 'Tam Coc La Montagne Resort & Spa',
    nameEn: 'Tam Coc La Montagne Resort & Spa',
    lat: 20.2015, lng: 105.9420,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 4,
    price: '1.500.000 – 3.000.000đ/đêm',
    priceEn: '1,500,000 – 3,000,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Nằm bên hồ sen yên tĩnh gần Tam Cốc, phòng phong cách cổ điển Pháp pha trộn nét Việt. View núi đá vôi hùng vĩ.',
    noteEn: 'Located by a quiet lotus lake near Tam Coc, French classical style blended with Vietnamese touches. Majestic limestone views.',
  },
  {
    name: 'Tràng An Retreat',
    nameEn: 'Trang An Retreat',
    lat: 20.2720, lng: 105.8950,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: '900.000 – 1.600.000đ/đêm',
    priceEn: '900,000 – 1,600,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Khu nghỉ dưỡng nhỏ xinh cạnh sông, rất gần bến thuyền Tràng An. Không gian yên bình, chủ nhà thân thiện, có hồ bơi ven sông.',
    noteEn: 'Charming riverside retreat, very close to Trang An boat station. Peaceful atmosphere, friendly hosts, riverside pool.',
  },
  {
    name: 'The Vancouver Hotel Ninh Bình',
    nameEn: 'The Vancouver Hotel Ninh Binh',
    lat: 20.2510, lng: 105.9765,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 3,
    price: '750.000 – 1.200.000đ/đêm',
    priceEn: '750,000 – 1,200,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Khách sạn boutique nổi tiếng với dịch vụ khách hàng xuất sắc tại trung tâm thành phố. Phòng sạch sẽ, hiện đại.',
    noteEn: 'Boutique hotel famous for excellent customer service in the city center. Clean, modern rooms.',
  },
  {
    name: 'Ninh Bình Valley Homestay',
    nameEn: 'Ninh Binh Valley Homestay',
    lat: 20.2115, lng: 105.9085,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: null,
    price: '700.000 – 1.300.000đ/đêm',
    priceEn: '700,000 – 1,300,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Những căn lều gỗ nằm biệt lập trong thung lũng, bao quanh là nước và núi rừng. Trải nghiệm hòa mình hoàn toàn với thiên nhiên.',
    noteEn: 'Isolated wooden bungalows in a valley, surrounded by water and mountains. A true immersion in nature.',
  },
  {
    name: 'Minawa Kenh Ga Resort & Spa',
    nameEn: 'Minawa Kenh Ga Resort & Spa',
    lat: 20.3155, lng: 105.8230,
    color: '#3b82f6',
    type: 'hotel',
    priority: true,
    stars: 5,
    price: '2.800.000 – 6.000.000đ/đêm',
    priceEn: '2,800,000 – 6,000,000 VND/night',
    checkin: '14h00', checkout: '12h00',
    note: 'Khu nghỉ dưỡng khoáng nóng cao cấp bên dòng sông Hoàng Long. Dịch vụ onsen chuẩn Nhật và trị liệu sức khỏe.',
    noteEn: 'Luxury hot spring resort by the Hoang Long River. Standard Japanese onsen services and wellness treatments.',
  },
];
