// ============================================================
//  NINH BÌNH AI — Nhà hàng & Mua sắm
//  File: nhahang.js
//
//  Hướng dẫn thêm địa điểm mới:
//  - Tọa độ lat/lng: Google Maps → click chuột phải → Sao chép tọa độ
//  - priority: true  → AI chủ động gợi ý khi tư vấn ăn uống / mua sắm
//  - priority: false → Chỉ hiển thị trên bản đồ
//  - type: 'food'  → Nhà hàng / quán ăn (màu vàng #f59e0b)
//  - type: 'shop'  → Mua sắm / quà lưu niệm (màu xanh lá #10b981)
// ============================================================

const RESTAURANTS = [
  {
    name: 'Heo Say Xỉn (GC22-23)',
    nameEn: 'Heo Say Xin (GC22-23)',
    lat: 20.2491, lng: 105.9768,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Gian hàng GC22-23, Phố cổ Hoa Lư',
    locationEn: 'Stall GC22-23, Hoa Lu Old Quarter',
    price: 'Tầm trung',
    priceEn: 'Mid-range',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Heo nuôi bằng rượu & thảo dược, da giòn thịt mềm. Đặc sản độc đáo "Vietnam\'s Kobe Pork". Nên đến sớm vì hay hết.',
    noteEn: 'Pork raised on rice wine & herbs, crispy skin, tender meat. "Vietnam\'s Kobe Pork". Arrive early — sells out fast.',
  },
  {
    name: 'Lẩu Gà Lá É (GC57-58)',
    nameEn: 'Lau Ga La E (GC57-58)',
    lat: 20.2488, lng: 105.9771,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Gian hàng GC57-58, Phố cổ Hoa Lư',
    locationEn: 'Stall GC57-58, Hoa Lu Old Quarter',
    price: '300.000 – 500.000đ/nồi (2–3 người)',
    priceEn: '300,000 – 500,000 VND/pot (2–3 people)',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Lẩu gà thảo mộc chuẩn vị Đà Lạt, nước dùng ngọt thanh từ lá é. Không gian chill, view phố cổ đẹp về đêm.',
    noteEn: 'Da Lat-style herb chicken hotpot, fragrant sweet broth. Chill vibe with great Old Quarter night view.',
  },
  {
    name: 'Đại Long Building — Cơm Cháy',
    nameEn: 'Dai Long Building — Burnt Rice',
    lat: 20.2540, lng: 105.9720,
    color: '#10b981',
    type: 'shop',
    priority: true,
    location: '325A Đường Lê Thái Tổ, Ninh Bình',
    locationEn: '325A Le Thai To Street, Ninh Binh',
    price: 'Nhiều mức giá',
    priceEn: 'Various price ranges',
    bestTime: 'Cả ngày',
    bestTimeEn: 'All day',
    note: 'Địa chỉ uy tín mua cơm cháy làm quà. Nhiều loại đóng gói sẵn, có thể ship về.',
    noteEn: 'Trusted address for burnt rice souvenirs. Various pre-packaged options, can be shipped.',
  },
  {
    name: 'Dê Chính Thư (Tràng An)',
    nameEn: 'Chinh Thu Goat Meat',
    lat: 20.2515, lng: 105.9182,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khê Thượng, Ninh Xuân, Hoa Lư',
    locationEn: 'Khe Thuong, Ninh Xuan, Hoa Lu',
    price: '200.000 – 400.000đ/người',
    priceEn: '200,000 – 400,000 VND/person',
    bestTime: 'Buổi trưa',
    bestTimeEn: 'Lunch time',
    note: 'Quán dê nổi tiếng nhất vùng Tràng An. Món dê tái chanh và cơm cháy sốt dê là "must-try". Không gian rất rộng.',
    noteEn: 'Most famous goat restaurant near Trang An. Must-try: lime-marinated goat and burnt rice with goat sauce.',
  },
  {
    name: 'Bún Chả Quạt Tình Mai',
    nameEn: 'Tinh Mai Grilled Pork Noodles',
    lat: 20.2522, lng: 105.9744,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '07 Phạm Hồng Thái, Phố 3, Ninh Bình',
    locationEn: '07 Pham Hong Thai, Ward 3, Ninh Binh',
    price: '40.000 – 60.000đ/bát',
    priceEn: '40,000 – 60,000 VND/bowl',
    bestTime: 'Sáng & Trưa',
    bestTimeEn: 'Morning & Lunch',
    note: 'Chả quạt miếng to, nướng cháy cạnh thơm lừng, ăn kèm bún lá. Đây là món ăn sáng/trưa đặc trưng của người dân thành phố.',
    noteEn: 'Big grilled pork patties, smoky and flavorful, served with leaf noodles. A signature local breakfast/lunch.',
  },
  {
    name: 'Miến Lươn Bà Phấn',
    nameEn: 'Ba Phan Eel Vermicelli',
    lat: 20.2558, lng: 105.9765,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: '99 Trần Hưng Đạo, Ninh Bình',
    locationEn: '99 Tran Hung Dao, Ninh Binh',
    price: '40.000 – 70.000đ',
    priceEn: '40,000 – 70,000 VND',
    bestTime: 'Buổi sáng',
    bestTimeEn: 'Morning',
    note: 'Nước dùng từ xương lươn và xương ống đậm đà. Lươn nhỏ nhưng thịt chắc và thơm.',
    noteEn: 'Rich broth made from eel and pork bones. Small but firm and fragrant eel meat.',
  },
  {
    name: 'Nhà hàng Đức Dê',
    nameEn: 'Duc De Restaurant',
    lat: 20.2578, lng: 105.9735,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '446 Nguyễn Huệ, Ninh Bình',
    locationEn: '446 Nguyen Hue, Ninh Binh',
    price: '250.000 – 500.000đ/người',
    priceEn: '250,000 – 500,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Thương hiệu dê núi lâu đời bậc nhất Ninh Bình. Nổi tiếng với kỹ thuật chế biến khử mùi hôi tuyệt đối. Không gian kiểu truyền thống.',
    noteEn: 'One of the oldest goat brands in Ninh Binh. Famous for its secret technique to remove the gamey smell. Traditional decor.',
  },
  {
    name: 'Gỏi Nhệch Vũ Bảo',
    nameEn: 'Vu Bao Rice Field Eel Salad',
    lat: 20.2612, lng: 105.9688,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '37 Nguyễn Huệ, Ninh Bình',
    locationEn: '37 Nguyen Hue, Ninh Binh',
    price: '200.000 – 350.000đ/người',
    priceEn: '200,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Đặc sản gỏi nhệch Kim Sơn. Ăn kèm rất nhiều loại lá rừng và nước chẻo nóng hổi, béo ngậy. Trải nghiệm ẩm thực cực kỳ độc đáo.',
    noteEn: 'Kim Son specialty eel salad. Served with various wild leaves and a rich, hot ginger-based sauce. A unique culinary experience.',
  },
  {
    name: 'Nhà hàng Thăng Long',
    nameEn: 'Thang Long Restaurant',
    lat: 20.2765, lng: 105.9185,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Tràng An, Trường Yên, Hoa Lư',
    locationEn: 'Trang An, Truong Yen, Hoa Lu',
    price: '150.000 – 300.000đ/người',
    priceEn: '150,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Nằm ngay gần chùa Bái Đính và Tràng An. Không gian cực rộng, phục vụ chuyên nghiệp các món dê núi, cơm cháy. Phù hợp cho khách đoàn.',
    noteEn: 'Located near Bai Dinh and Trang An. Spacious area, professional service for goat meat and burnt rice. Ideal for groups.',
  },
  {
    name: 'Chim Trời Bình Dũng',
    nameEn: 'Binh Dung Wild Birds',
    lat: 20.2545, lng: 105.9812,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Phố 4, Đông Thành, Ninh Bình',
    locationEn: 'Ward 4, Dong Thanh, Ninh Binh',
    price: '200.000 – 400.000đ/người',
    priceEn: '200,000 – 400,000 VND/person',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Chuyên các món chim trời: sẻ, ngói, sâm cầm, vịt trời. Chế biến theo kiểu dân dã nhưng hương vị cực kỳ đậm đà.',
    noteEn: 'Specializes in wild birds: sparrows, snipes, wild ducks. Rustic cooking style with rich flavors.',
  },
];
