// ============================================================
//  NINH BÌNH AI — Nhà hàng & Mua sắm
//  File: nhahang.js
//
//  Hướng dẫn thêm địa điểm mới:
//  - Tọa độ lat/lng: Google Maps → click chuột phải → Sao chép tọa độ
//  - priority: true  → AI chủ động gợi ý khi tư vấn ăn uống / mua sắm
//  - priority: false → Chỉ hiển thị trên bản đồ
//  - type: 'food'  → Nhà hàng / quán ăn (màu vàng #f59e0b)
//  - type: 'shop'  → Mua sắm / quà lưu niệm (màu xanh lá #10b981)
// ============================================================

const RESTAURANTS = [
  {
    name: 'Heo Say Xỉn (GC22-23)',
    nameEn: 'Heo Say Xin (GC22-23)',
    lat: 20.2491, lng: 105.9768,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Gian hàng GC22-23, Phố cổ Hoa Lư',
    locationEn: 'Stall GC22-23, Hoa Lu Old Quarter',
    price: 'Tầm trung',
    priceEn: 'Mid-range',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Heo nuôi bằng rượu & thảo dược, da giòn thịt mềm. Đặc sản độc đáo "Vietnam\'s Kobe Pork". Nên đến sớm vì hay hết.',
    noteEn: 'Pork raised on rice wine & herbs, crispy skin, tender meat. "Vietnam\'s Kobe Pork". Arrive early — sells out fast.',
  },
  {
    name: 'Lẩu Gà Lá É (GC57-58)',
    nameEn: 'Lau Ga La E (GC57-58)',
    lat: 20.2488, lng: 105.9771,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Gian hàng GC57-58, Phố cổ Hoa Lư',
    locationEn: 'Stall GC57-58, Hoa Lu Old Quarter',
    price: '300.000 – 500.000đ/nồi (2–3 người)',
    priceEn: '300,000 – 500,000 VND/pot (2–3 people)',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Lẩu gà thảo mộc chuẩn vị Đà Lạt, nước dùng ngọt thanh từ lá é. Không gian chill, view phố cổ đẹp về đêm.',
    noteEn: 'Da Lat-style herb chicken hotpot, fragrant sweet broth. Chill vibe with great Old Quarter night view.',
  },
  {
    name: 'Đại Long Building — Cơm Cháy',
    nameEn: 'Dai Long Building — Burnt Rice',
    lat: 20.2540, lng: 105.9720,
    color: '#10b981',
    type: 'shop',
    priority: true,
    location: '325A Đường Lê Thái Tổ, Ninh Bình',
    locationEn: '325A Le Thai To Street, Ninh Binh',
    price: 'Nhiều mức giá',
    priceEn: 'Various price ranges',
    bestTime: 'Cả ngày',
    bestTimeEn: 'All day',
    note: 'Địa chỉ uy tín mua cơm cháy làm quà. Nhiều loại đóng gói sẵn, có thể ship về.',
    noteEn: 'Trusted address for burnt rice souvenirs. Various pre-packaged options, can be shipped.',
  },
  {
    name: 'Dê Chính Thư (Tràng An)',
    nameEn: 'Chinh Thu Goat Meat',
    lat: 20.2515, lng: 105.9182,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Khê Thượng, Ninh Xuân, Hoa Lư',
    locationEn: 'Khe Thuong, Ninh Xuan, Hoa Lu',
    price: '200.000 – 400.000đ/người',
    priceEn: '200,000 – 400,000 VND/person',
    bestTime: 'Buổi trưa',
    bestTimeEn: 'Lunch time',
    note: 'Quán dê nổi tiếng nhất vùng Tràng An. Món dê tái chanh và cơm cháy sốt dê là "must-try". Không gian rất rộng.',
    noteEn: 'Most famous goat restaurant near Trang An. Must-try: lime-marinated goat and burnt rice with goat sauce.',
  },
  {
    name: 'Bún Chả Quạt Tình Mai',
    nameEn: 'Tinh Mai Grilled Pork Noodles',
    lat: 20.2522, lng: 105.9744,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '07 Phạm Hồng Thái, Phố 3, Ninh Bình',
    locationEn: '07 Pham Hong Thai, Ward 3, Ninh Binh',
    price: '40.000 – 60.000đ/bát',
    priceEn: '40,000 – 60,000 VND/bowl',
    bestTime: 'Sáng & Trưa',
    bestTimeEn: 'Morning & Lunch',
    note: 'Chả quạt miếng to, nướng cháy cạnh thơm lừng, ăn kèm bún lá. Đây là món ăn sáng/trưa đặc trưng của người dân thành phố.',
    noteEn: 'Big grilled pork patties, smoky and flavorful, served with leaf noodles. A signature local breakfast/lunch.',
  },
  {
    name: 'Miến Lươn Bà Phấn',
    nameEn: 'Ba Phan Eel Vermicelli',
    lat: 20.2558, lng: 105.9765,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: '99 Trần Hưng Đạo, Ninh Bình',
    locationEn: '99 Tran Hung Dao, Ninh Binh',
    price: '40.000 – 70.000đ',
    priceEn: '40,000 – 70,000 VND',
    bestTime: 'Buổi sáng',
    bestTimeEn: 'Morning',
    note: 'Nước dùng từ xương lươn và xương ống đậm đà. Lươn nhỏ nhưng thịt chắc và thơm.',
    noteEn: 'Rich broth made from eel and pork bones. Small but firm and fragrant eel meat.',
  },
  {
    name: 'Nhà hàng Đức Dê',
    nameEn: 'Duc De Restaurant',
    lat: 20.2578, lng: 105.9735,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '446 Nguyễn Huệ, Ninh Bình',
    locationEn: '446 Nguyen Hue, Ninh Binh',
    price: '250.000 – 500.000đ/người',
    priceEn: '250,000 – 500,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Thương hiệu dê núi lâu đời bậc nhất Ninh Bình. Nổi tiếng với kỹ thuật chế biến khử mùi hôi tuyệt đối. Không gian kiểu truyền thống.',
    noteEn: 'One of the oldest goat brands in Ninh Binh. Famous for its secret technique to remove the gamey smell. Traditional decor.',
  },
  {
    name: 'Gỏi Nhệch Vũ Bảo',
    nameEn: 'Vu Bao Rice Field Eel Salad',
    lat: 20.2612, lng: 105.9688,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '37 Nguyễn Huệ, Ninh Bình',
    locationEn: '37 Nguyen Hue, Ninh Binh',
    price: '200.000 – 350.000đ/người',
    priceEn: '200,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Đặc sản gỏi nhệch Kim Sơn. Ăn kèm rất nhiều loại lá rừng và nước chẻo nóng hổi, béo ngậy. Trải nghiệm ẩm thực cực kỳ độc đáo.',
    noteEn: 'Kim Son specialty eel salad. Served with various wild leaves and a rich, hot ginger-based sauce. A unique culinary experience.',
  },
  {
    name: 'Nhà hàng Thăng Long',
    nameEn: 'Thang Long Restaurant',
    lat: 20.2765, lng: 105.9185,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Tràng An, Trường Yên, Hoa Lư',
    locationEn: 'Trang An, Truong Yen, Hoa Lu',
    price: '150.000 – 300.000đ/người',
    priceEn: '150,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Nằm ngay gần chùa Bái Đính và Tràng An. Không gian cực rộng, phục vụ chuyên nghiệp các món dê núi, cơm cháy. Phù hợp cho khách đoàn.',
    noteEn: 'Located near Bai Dinh and Trang An. Spacious area, professional service for goat meat and burnt rice. Ideal for groups.',
  },
  {
    name: 'Chim Trời Bình Dũng',
    nameEn: 'Binh Dung Wild Birds',
    lat: 20.2545, lng: 105.9812,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Phố 4, Đông Thành, Ninh Bình',
    locationEn: 'Ward 4, Dong Thanh, Ninh Binh',
    price: '200.000 – 400.000đ/người',
    priceEn: '200,000 – 400,000 VND/person',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Chuyên các món chim trời: sẻ, ngói, sâm cầm, vịt trời. Chế biến theo kiểu dân dã nhưng hương vị cực kỳ đậm đà.',
    noteEn: 'Specializes in wild birds: sparrows, snipes, wild ducks. Rustic cooking style with rich flavors.',
  },
  {
    name: 'Nhà hàng Khoa Anh',
    nameEn: 'Khoa Anh Restaurant',
    lat: 20.2178, lng: 105.9230,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Thôn Đam Khê, Ninh Hải, Hoa Lư',
    locationEn: 'Dam Khe Village, Ninh Hai, Hoa Lu',
    price: '150.000 – 350.000đ/người',
    priceEn: '150,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'View nhìn ra cánh đồng lúa và dòng sông Ngô Đồng. Không gian mở rất thoáng. Chuyên thịt dê núi và cá sông.',
    noteEn: 'Overlooking rice fields and Ngo Dong river. Open-air space. Specializes in mountain goat and river fish.',
  },
  {
    name: 'Family Restaurant',
    nameEn: 'Family Restaurant',
    lat: 20.2192, lng: 105.9250,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Đường vào bến thuyền Tam Cốc',
    locationEn: 'Tam Coc Wharf access road',
    price: '80.000 – 200.000đ/người',
    priceEn: '80,000 – 200,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Quán ăn gia đình ấm cúng, menu phong phú từ cơm Việt đến các món Pizza, Pasta cho khách quốc tế.',
    noteEn: 'Cozy family-run eatery, diverse menu from Vietnamese rice to Pizza/Pasta for international tourists.',
  },
  {
    name: 'The Banana Tree Hostel (Pool Bar & Resto)',
    nameEn: 'The Banana Tree Hostel',
    lat: 20.2180, lng: 105.9248,
    color: '#f59e0b', // Có thể dùng màu riêng cho Bar/Resto
    type: 'food',
    priority: true,
    location: 'Cạnh bến thuyền Tam Cốc',
    locationEn: 'Next to Tam Coc Wharf',
    price: '100.000 – 300.000đ',
    priceEn: '100,000 – 300,000 VND',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Không gian cực chill có bể bơi, nhạc hay. Thích hợp cho giới trẻ ăn tối và uống cocktail ngắm nhìn bến thuyền.',
    noteEn: 'Chill vibe with a pool and good music. Perfect for young travelers for dinner and cocktails.',
  },
  {
    name: 'Nhà hàng Linh Chi',
    nameEn: 'Linh Chi Restaurant',
    lat: 20.2170, lng: 105.9235,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Đội 1, Văn Lâm, Ninh Hải',
    locationEn: 'Group 1, Van Lam, Ninh Hai',
    price: '120.000 – 250.000đ/người',
    priceEn: '120,000 – 250,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Chuyên cơm cháy chà bông tự làm và các món từ vịt cỏ. Giá cả rất phải chăng ngay tại khu du lịch.',
    noteEn: 'Specializes in homemade burnt rice and local grass duck. Very reasonable prices in the heart of the tourist area.',
  },
  {
    name: 'Nhà hàng Ba Cửa',
    nameEn: 'Ba Cua Restaurant',
    lat: 20.2707, lng: 105.9137,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Thôn Tràng An, Trường Yên, Hoa Lư',
    locationEn: 'Trang An Hamlet, Truong Yen, Hoa Lu',
    price: '200.000 – 300.000đ/người',
    priceEn: '200,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Nằm ngay trong vùng lõi di sản. Không gian sân vườn cực rộng, gần gũi thiên nhiên. Đặc sản dê núi ủ trấu và cá rô Tổng Trường rất ngon.',
    noteEn: 'Located in the heart of the heritage site. Spacious garden setting. Famous for straw-roasted goat and Tong Truong fish.',
  },
  {
    name: 'Dũng Phố Núi',
    nameEn: 'Dung Pho Nui Restaurant',
    lat: 20.2525, lng: 105.9260,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Ninh Xuân, Hoa Lư (Gần bến thuyền Tràng An)',
    locationEn: 'Ninh Xuan, Hoa Lu (Near Trang An Wharf)',
    price: '150.000 – 350.000đ/người',
    priceEn: '150,000 – 350,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Quán rất đông khách nhờ hương vị dê núi chuẩn truyền thống. Phục vụ nhanh, menu đa dạng các món từ dê tái chanh đến dê xào lăn.',
    noteEn: 'Very popular for authentic traditional goat dishes. Fast service and a diverse menu from lime-marinated to stir-fried goat.',
  },
  {
    name: 'Tràng An Riverside Garden',
    nameEn: 'Trang An Riverside Garden',
    lat: 20.2492, lng: 105.9322,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Thôn Khê Thượng, Ninh Xuân, Hoa Lư',
    locationEn: 'Khe Thuong Hamlet, Ninh Xuan, Hoa Lu',
    price: '100.000 – 300.000đ',
    priceEn: '100,000 – 300,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'View sát sông cực chill, không gian sạch sẽ, hiện đại. Ngoài đặc sản địa phương còn có các món Tây và nước ép tươi ngon.',
    noteEn: 'Stunning riverside view, clean and modern space. Offers local specialties along with Western dishes and fresh juices.',
  },
  {
    name: 'Nhà hàng Quốc Quân',
    nameEn: 'Quoc Quan Restaurant',
    lat: 20.2744, lng: 105.9126,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Tràng An, Trường Yên, Hoa Lư',
    locationEn: 'Trang An, Truong Yen, Hoa Lu',
    price: '150.000 – 300.000đ/người',
    priceEn: '150,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Chuyên phục vụ khách đoàn và gia đình. Không gian thoáng, có chỗ đậu xe rộng rãi, thuận tiện cho khách tham quan cố đô Hoa Lư.',
    noteEn: 'Specializes in serving groups and families. Open space with large parking, convenient for visitors to Hoa Lu Ancient Capital.',
  },
  {
    name: 'Trang An Local Cuisine',
    nameEn: 'Trang An Local Cuisine',
    lat: 20.2644, lng: 105.9146,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Trường Yên, Hoa Lư (Gần bến thuyền)',
    locationEn: 'Truong Yen, Hoa Lu (Near the wharf)',
    price: '80.000 – 250.000đ',
    priceEn: '80,000 – 250,000 VND',
    bestTime: 'Cả ngày',
    bestTimeEn: 'All day',
    note: 'Sự kết hợp giữa ẩm thực bản địa và không gian Cafe/Cocktail. Trang trí đẹp mắt, phù hợp cho khách thích check-in.',
    noteEn: 'A blend of local cuisine and Cafe/Cocktail space. Beautifully decorated, perfect for photo enthusiasts.',
  },
  {
    name: 'Nhà hàng Cao Sơn',
    nameEn: 'Cao Son Restaurant',
    lat: 20.2458, lng: 105.8752,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Xã Gia Sinh, Gia Viễn (Gần cổng chùa Bái Đính)',
    locationEn: 'Gia Sinh, Gia Vien (Near Bai Dinh Pagoda Gate)',
    price: '150.000 – 350.000đ/người',
    priceEn: '150,000 – 350,000 VND/person',
    bestTime: 'Buổi trưa',
    bestTimeEn: 'Lunch time',
    note: 'Một trong những nhà hàng lớn và uy tín nhất khu vực Bái Đính. Chuyên cơm cháy, dê núi các món. Không gian sang trọng, phục vụ chuyên nghiệp.',
    noteEn: 'One of the largest and most reputable restaurants near Bai Dinh. Specialized in burnt rice and various goat dishes. Professional service.',
  },
  {
    name: 'Buffet Chay chùa Bái Đính',
    nameEn: 'Bai Dinh Pagoda Vegan Buffet',
    lat: 20.2440, lng: 105.8715,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Trong khuôn viên chùa Bái Đính',
    locationEn: 'Inside Bai Dinh Pagoda Complex',
    price: '100.000 – 150.000đ/người',
    priceEn: '100,000 – 150,000 VND/person',
    bestTime: 'Buổi trưa',
    bestTimeEn: 'Lunch time',
    note: 'Trải nghiệm ẩm thực chay thanh tịnh ngay tại chùa. Nhiều món ăn đa dạng từ nông sản địa phương. Phù hợp cho khách hành hương.',
    noteEn: 'A peaceful vegan dining experience inside the pagoda. Variety of dishes made from local produce. Ideal for pilgrims.',
  },
  {
    name: 'Nhà hàng Bái Đính Garden',
    nameEn: 'Bai Dinh Garden Restaurant',
    lat: 20.2395, lng: 105.8770,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Thôn 5, Gia Sinh (Gần chùa Bái Đính)',
    locationEn: 'Hamlet 5, Gia Sinh (Near Bai Dinh Pagoda)',
    price: '250.000 – 500.000đ/người',
    priceEn: '250,000 – 500,000 VND/person',
    bestTime: 'Tối (Dinner)',
    bestTimeEn: 'Evening',
    note: 'Không gian cao cấp, yên tĩnh nằm trong khu nghỉ dưỡng. Menu kết hợp hài hòa giữa ẩm thực truyền thống và hiện đại.',
    noteEn: 'Upscale and quiet setting within a resort. The menu harmoniously combines traditional and modern cuisine.',
  },
  {
    name: 'Tiệm Trà Chanh Phố Cổ (GC01)',
    nameEn: 'Ancient Town Tea Stall (GC01)',
    lat: 20.2495, lng: 105.9760,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Gian hàng GC01, Phố cổ Hoa Lư',
    locationEn: 'Stall GC01, Hoa Lu Old Quarter',
    price: '20.000 – 50.000đ',
    priceEn: '20,000 – 50,000 VND',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Vị trí đắc địa ngay lối vào, view trực diện hồ Kỳ Lân. Phù hợp để ngồi uống trà, ngắm dòng người qua lại và xem biểu diễn nghệ thuật.',
    noteEn: 'Prime location at the entrance with a direct view of Ky Lan Lake. Perfect for sipping tea and watching street performances.',
  },
  {
    name: 'Quầy Bánh Rán Phố Cổ',
    nameEn: 'Old Quarter Fried Pancakes',
    lat: 20.2492, lng: 105.9772,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Khu ẩm thực đường phố, Phố cổ Hoa Lư',
    locationEn: 'Street Food Area, Hoa Lu Old Quarter',
    price: '5.000 – 15.000đ/chiếc',
    priceEn: '5,000 – 15,000 VND/piece',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Món ăn vặt không thể bỏ qua khi dạo phố. Bánh nóng hổi, giòn tan, ăn kèm nước mắm chua ngọt.',
    noteEn: 'Must-try street snack. Crispy, hot pancakes served with sweet and sour dipping sauce.',
  },
  {
    name: 'Thịt Xiên Nướng Phố Cổ',
    nameEn: 'Old Quarter Grilled Pork Skewers',
    lat: 20.2490, lng: 105.9775,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Dãy gian hàng ẩm thực Phố cổ',
    locationEn: 'Food Stall Row, Old Quarter',
    price: '10.000 – 20.000đ/xiên',
    priceEn: '10,000 – 20,000 VND/skewer',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Mùi thơm nức mũi của thịt nướng lan tỏa khắp phố. Thích hợp vừa đi bộ vừa thưởng thức.',
    noteEn: 'The irresistible aroma of grilled meat fills the street. Great for snacking while walking.',
  },
  {
    name: 'Chookie\'s Beer Garden',
    nameEn: 'Chookie\'s Beer Garden',
    lat: 20.2168, lng: 105.9411,
    color: '#06b6d4', // Màu xanh Cyan cho các quán chill/bar
    type: 'food',
    priority: true,
    location: 'Đường Tam Cốc, Ninh Hải, Hoa Lư',
    locationEn: 'Tam Coc Rd, Ninh Hai, Hoa Lu',
    price: '100.000 – 300.000đ',
    priceEn: '100,000 – 300,000 VND',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Điểm tụ tập số 1 của giới trẻ và khách du lịch bụi. Menu đa dạng từ Pizza, Burger đến bia thủ công. Không gian sân vườn cực rộng và thoải mái.',
    noteEn: 'Top spot for backpackers and youth. Diverse menu from Pizza, Burgers to craft beer. Spacious garden vibe.',
  },
  {
    name: 'Tầng 6 Heli Coffee',
    nameEn: 'Heli Coffee (6th Floor)',
    lat: 20.2640, lng: 105.9641,
    color: '#06b6d4',
    type: 'food',
    priority: true,
    location: 'Tòa nhà Phương Anh, Tràng An, Hoa Lư',
    locationEn: 'Phuong Anh Building, Trang An, Hoa Lu',
    price: '35.000 – 60.000đ',
    priceEn: '35,000 – 60,000 VND',
    bestTime: 'Hoàng hôn (Sunset)',
    bestTimeEn: 'Sunset',
    note: 'Quán cafe rooftop có view nhìn toàn cảnh thành phố và khu vực Tràng An. Góc check-in "vô cực" cực hot vào lúc chiều tà.',
    noteEn: 'Rooftop cafe with panoramic views of the city and Trang An. Famous "infinity" photo corners at sunset.',
  },
  {
    name: 'Nhà hàng Tam Gia Trang',
    nameEn: 'Tam Gia Trang Restaurant',
    lat: 20.2625, lng: 105.9646,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: '35 Tràng An 2, Tân Thành, Hoa Lư',
    locationEn: '35 Trang An 2, Tan Thanh, Hoa Lu',
    price: '150.000 – 300.000đ/người',
    priceEn: '150,000 – 300,000 VND/person',
    bestTime: 'Trưa & Tối',
    bestTimeEn: 'Lunch & Dinner',
    note: 'Thiết kế theo phong cách kiếm hiệp độc đáo. Đồ ăn ngon, trang trí đẹp mắt, rất thích hợp cho nhóm bạn trẻ thích trải nghiệm lạ.',
    noteEn: 'Unique "Martial Arts" (Wuxia) themed decor. Good food and great for young groups seeking a themed experience.',
  },
  {
    name: 'Kem xôi Thanh Hằng',
    nameEn: 'Thanh Hang Sticky Rice Ice Cream',
    lat: 20.2572, lng: 105.9705,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: '36 Cù Chính Lan, Hoa Lư',
    locationEn: '36 Cu Chinh Lan, Hoa Lu',
    price: '20.000 – 40.000đ',
    priceEn: '20,000 – 40,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Quán ăn vặt "huyền thoại" tại Ninh Bình. Kem xôi dẻo thơm, ngọt mát, giá cực sinh viên.',
    noteEn: 'Legendary snack spot. Creamy ice cream with fragrant sticky rice at student-friendly prices.',
  },
  {
    name: 'The Aria Cafe',
    nameEn: 'The Aria Cafe',
    lat: 20.2715, lng: 105.9772,
    color: '#06b6d4',
    type: 'food',
    priority: true,
    location: '144A4 Lê Hồng Phong, Hoa Lư',
    locationEn: '144A4 Le Hong Phong, Hoa Lu',
    price: '40.000 – 80.000đ',
    priceEn: '40,000 – 80,000 VND',
    bestTime: 'Sáng & Chiều',
    bestTimeEn: 'Morning & Afternoon',
    note: 'Phong cách Châu Âu sang chảnh với bể bơi ngoài trời. Là địa điểm "sống ảo" hàng đầu của các bạn trẻ tại Ninh Bình.',
    noteEn: 'Elegant European style with an outdoor pool. A top-tier check-in spot for local youth.',
  },
  {
    name: 'Brick Coffee Shop',
    nameEn: 'Brick Coffee Shop',
    lat: 20.2555, lng: 105.9722,
    color: '#06b6d4',
    type: 'food',
    priority: true,
    location: 'Số 2, Ngõ 10, Đào Duy Từ, Hoa Lư',
    locationEn: 'No. 2, Alley 10, Dao Duy Tu, Hoa Lu',
    price: '30.000 – 55.000đ',
    priceEn: '30,000 – 55,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Quán decor theo phong cách industrial với gạch trần cực nghệ. Không gian yên tĩnh, nhạc gu rất chất, là nơi trốn nóng tuyệt vời cho các bạn trẻ.',
    noteEn: 'Industrial style with raw bricks. Quiet space, great music, a perfect hideaway for youth.',
  },
  {
    name: 'Mona Lisa Tam Coc',
    nameEn: 'Mona Lisa Tam Coc',
    lat: 20.2182, lng: 105.9238,
    color: '#f59e0b',
    type: 'food',
    priority: true,
    location: 'Trung tâm khu du lịch Tam Cốc',
    locationEn: 'Tam Coc Tourist Center',
    price: '150.000 – 400.000đ',
    priceEn: '150,000 – 400,000 VND',
    bestTime: 'Buổi tối',
    bestTimeEn: 'Evening',
    note: 'Sự giao thoa ẩm thực Ý - Việt. Pizza lò củi cực ngon và không gian ban công nhìn xuống phố đi bộ Tam Cốc rất nhộn nhịp.',
    noteEn: 'Italian-Vietnamese fusion. Excellent wood-fired pizza and a balcony overlooking the bustling Tam Coc street.',
  },
  {
    name: 'Sân Cafe & Bistro',
    nameEn: 'San Cafe & Bistro',
    lat: 20.2515, lng: 105.9765,
    color: '#06b6d4',
    type: 'food',
    priority: true,
    location: 'Khu biệt thự ven hồ Kỳ Lân, Hoa Lư',
    locationEn: 'Ky Lan Lakeside Villas, Hoa Lu',
    price: '45.000 – 120.000đ',
    priceEn: '45,000 – 120,000 VND',
    bestTime: 'Chiều & Tối',
    bestTimeEn: 'Afternoon & Evening',
    note: 'Không gian mở hiện đại, tinh tế. Thích hợp cho những buổi hẹn hò sang trọng hoặc gặp gỡ đối tác trong không gian yên tĩnh.',
    noteEn: 'Modern, sophisticated open space. Ideal for elegant dates or business meetings in a quiet atmosphere.',
  },
  {
    name: 'Chè Bưởi & Đồ Ăn Vặt Cô Lan',
    nameEn: 'Co Lan Grapefruit Sweet Soup',
    lat: 20.2565, lng: 105.9730,
    color: '#f59e0b',
    type: 'food',
    priority: false,
    location: 'Ngõ 2 Lương Văn Tụy, Hoa Lư',
    locationEn: 'Alley 2 Luong Van Tuy, Hoa Lu',
    price: '15.000 – 35.000đ',
    priceEn: '15,000 – 35,000 VND',
    bestTime: 'Buổi chiều',
    bestTimeEn: 'Afternoon',
    note: 'Chè bưởi giòn sần sật, cốt dừa béo ngậy. Quán nằm trong ngõ nhỏ nhưng luôn tấp nập khách trẻ.',
    noteEn: 'Crunchy grapefruit sweet soup with rich coconut milk. Tucked in a small alley but always crowded with locals.',
  },
  
];
